### ISSUE TITLE
bug: Cannot Run with nVIDIA

### ISSUE THREAD

**Issue by MiRinChan** [Martichou/rquickshare#220] opened 2024-10-17 06:53 UTC
It seem a tauri and nvidia problem, however I still cannot run it with `WEBKIT_DISABLE_COMPOSITING_MODE=1` environment.

How to Reproduce:
```bash
$ nix shell nixpkgs#rquickshare
$ rquickshare

Gtk-Message: 14:45:03.892: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:45:03.892: Failed to load module "window-decorations-gtk-module"
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)

$ WEBKIT_DISABLE_COMPOSITING_MODE=1 rquickshare

Gtk-Message: 14:50:52.740: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:50:52.740: Failed to load module "window-decorations-gtk-module"
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
```

Some infomation: 
- NixOS 24.11 (Vicuna)（64 bit）
- Linux 6.10.12
- Graphic card Driver version: 4.6.0 NVIDIA 560.35.03

**Comment by jdev082** [comment] 2024-10-21 19:05
Can reproduce

NixOS 24.11
Linux 6.6.57
NVIDIA 560.35.03

I suspect that this is a problem with the nix package of rquickshare

```
$ rquickshare

Gtk-Message: 14:03:49.670: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:03:49.670: Failed to load module "window-decorations-gtk-module"
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
```

```$ WEBKIT_DISABLE_COMPOSITING_MODE=1 rquickshare

Gtk-Message: 14:04:25.146: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:04:25.146: Failed to load module "window-decorations-gtk-module"
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
```

**Comment by jdev082** [comment] 2024-10-30 23:59
https://github.com/NixOS/nixpkgs/issues/350315

**Comment by Gregman-js** [comment] 2024-11-01 09:54
I use fedora 41 with gnome 47 and I have the same problem after installing nvidia drivers.
How I installed drivers: https://rpmfusion.org/Howto/NVIDIA#Current_GeForce.2FQuadro.2FTesla
```
user@fedora:~/r-quick-share$ ./r-quick-share.AppImage 
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
Segmentation fault (core dumped)
```

**Comment by jdev082** [comment] 2024-11-03 18:38
The [AppImage that uses glibc 2.31](https://github.com/Martichou/rquickshare/releases/download/v0.11.2/r-quick-share-legacy_v0.11.2_glibc-2.31_amd64.AppImage) works on my system, while the glibc 2.39 variant does not. I'm guessing distributions probably ship the glibc 2.39 variant. The non-working variant is what my distro (NixOS) has.

**Comment by Martichou** [comment] 2024-11-09 10:14
Hey! So did both of you ended up with a working solution?
Releasing an app for linux is kind of a hard task as you have to handle multiple system and all, that's why I'm already duplicating the work by maintaining two version of Tauri to support multiple version of GTK and Glibc.

So sometime you may have to try different image until one works for your system.
I'm going to close this issue as it seems both of you found an image to use, if that's not the case, just reply and I'll reopen :)

**Closed by Martichou** 2024-11-09 10:14 UTC

**Comment by MiRinChan** [comment] 2024-11-09 11:43
> Hey! So did both of you ended up with a working solution?... [reply this one](https://github.com/Martichou/rquickshare/issues/220#issuecomment-2466159324)

Uhm.. You are right.

I'm using NixOS but the dependence version is depend on maintainer who is pack it. And I found it using [glibc-2.39](https://github.com/r-ryantm/nixpkgs/commit/c9f3e91a2ea11d4da84a63693300fe0ba680855d) version. But I use Nix package stable channel that still using v0.8.2. However I will try another one like glibc-2.31, if it work I will tell you guys!

Thanks for your working and reply, respect.

**Comment by MiRinChan** [comment] 2024-11-09 12:33
Hi, [@]Martichou developer, [@]jdev082 [@]Gregman-js  you guys have same issue like me.

Just like developer said, it is dependence issue. Now I [figure](https://github.com/MiRinChan/MaybeANixOSConfig/blob/9774d83aaa00342ce52af73497bd179e315fa632/pkgs/RQuickShare.nix) it. Use legacy edition and work fine.

![image](https://github.com/user-attachments/assets/a0a5427d-7511-40dd-b986-6214bcddc874)

**Comment by automaticbulb** [comment] 2025-03-15 11:59
I'm getting the error 

> Could not create GBM EGL display: EGL_NOT_INITIALIZED. Aborting...

after updating my Nvidia driver to a more recent one, 570.86.16, even if I use the suggested

>env WEBKIT_DISABLE_COMPOSITING_MODE=1 rquickshare

I tried to install the legacy version since that seems to be another workaround but then I get an error about a dependency

>Dependency is not satisfiable: libwebkit2gtk-4.0-37

when attempting to install.

Any ideas where to go from there? I really liked being able to QuickShare stuff. It worked so well before this blasted Nvidia driver! I'm on Mint 22.1.
