### ISSUE TITLE
Bug: Gnome doesn't have tray icons so the app runs in the background once opened and u can never re-open it until you kill it manually

### ISSUE THREAD

**Issue by 103sbavert** [Martichou/rquickshare#129] opened 2024-07-11 19:44 UTC
Since gnome doesn't have a system tray, unless u use the extension ofc, the app stays open in the background instead of gracefully closing. Even if unselect the "Keep running on close", it keeps running (as reported by ps) and can only be killed with manual killall command. Plus, it won't just bring the window to focus if u just click on the launcher icon again.

Version: 0.10.1
OS: Arch Linux
Package: r-quick-share (non-bin)

**Comment by Martichou** [comment] 2024-07-11 20:10
Strange.. I'm guessing the aur package is using the legacy version. I'm gonna double check on my side that it's still working for me. And I may ask you for logs with TRACE level if I can't reproduce.

**Comment by vvvvvvitor** [comment] 2024-07-26 00:23
Can confirm it also happens with RPM on Fedora.


https://github.com/user-attachments/assets/7432d3cb-3d7a-4186-9d7b-2101c72eb6c4

**Comment by Yiannis128** [comment] 2024-08-02 14:51
This is not an issue on Fedora 40

**Comment by vvvvvvitor** [comment] 2024-08-02 15:32
> This is not an issue on Fedora 40

I'm using the lastest version

**Comment by Yiannis128** [comment] 2024-08-02 15:57
> > This is not an issue on Fedora 40
> 
> I'm using the lastest version

OK, I am just saying I am not having any issues personally 😅

**Comment by Martichou** [comment] 2024-08-05 18:06
@vvvvvvitor would you be able to send me the log file when you produce the error (closing when the option is not selected to keep running on close) with TRACE level as explained here: https://github.com/Martichou/rquickshare/pull/104 ?

**Comment by Martichou** [comment] 2024-08-05 18:06
Can you also send me the content of the config file while we're at it to ensure the setting is correctly defined for the keep running on close?

**Closed** 2024-08-05 22:04 UTC

**Comment by vvvvvvitor** [comment] 2024-08-06 00:45
> Can you also send me the content of the config file while we're at it to ensure the setting is correctly defined for the keep running on close?
> 
> Edit: closing as should be fixed by #146. If not don't hesitate to reopen with the logs. In the meantime (before release), you should be able to use debug build from here: https://github.com/Martichou/rquickshare/actions/runs/10256675307

Do you still want me to send the logs?
